name: Build & Release Signed APK

on:
  push:
    tags:
      - "v*"  # Hanya berjalan saat ada tag versi baru (misal v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore release-key.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "mypassword" -keypass "mypassword" \
            -alias "my-key-alias" -dname "CN=MyApp, OU=Org, O=Company, L=City, S=State, C=ID"

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore release-key.jks \
            -storepass "mypassword" -keypass "mypassword" \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            "my-key-alias"

      - name: Verify APK Signature
        run: jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Align APK
        run: |
          $ANDROID_HOME/build-tools/33.0.1/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
